# Configuration for BSides Oslo. This
# file contains most of the variables for the information on the website.

title: BSides Oslo 2023

description: "BSides Oslo is an inclusive community driven information security event."
event:
  date: "September 21, 2023"
  venue: "Vulkan Arena"

baseurl: ""

twitter_username: OsloBSides
youtube_channel: https://youtube.com/bsidesoslo

cfp:
  form: https://docs.google.com/forms/d/1JVU1rPNBI9e-5hyT_q87jkhS7SrVx_vQc9Lll7aar9Y
  deadline: "Jun 30th, 2023 23:59 CET"

emails:
  info: info@bsidesoslo.no
  sponsors: sponsors@bsidesoslo.no
  cfp: cfp@bsidesoslo.no

social:
- title: mastodon
  url: https://infosec.exchange/@bsidesoslo
  social: true
- title: twitter
  url: https://twitter.com/OsloBSides
  social: true
- title: youtube
  url: https://youtube.com/bsidesoslo
  social: true
- title: envelope
  url: mailto:info@bsidesoslo.no

# Build settings

exclude: 
- .gitignore
- README.md
- LICENSE
- Dockerfile
- CNAME
- CODE_OF_CONDUCT.md
  

menu:
- title: CFP
  url: "/#cfp"
- title: Tickets
  url: "https://www.deltager.no/event/bsidesoslo2023"
- title: About
  url: "/#about"
- title: Code of Conduct
  url: "/code-of-conduct"

# Feature toggle specific sections
sections:
  cfp: true
  speakers: false


collections:
  talks:
    output: true
